---
- name: clone agora-ciudadana
  git: repo=https://github.com/pirata-cat/agora-ciudadana.git
       dest="{{agora.root}}"
       version=master

- name: create virtualenv
  shell: /bin/bash -c 'virtualenv {{agora.virtualenv.root}}'
  args:
    creates: "{{agora.virtualenv.root}}"

- name: install dependencies
  pip: requirements=requirements.txt
       virtualenv="{{agora.virtualenv.root}}"
       chdir="{{agora.root}}"

- name: install custom dependencies
  pip: name=psycopg2
       virtualenv="{{agora.virtualenv.root}}"

- name: install local config
  template: src=settings.py
            dest="{{agora.root}}/agora_site/custom_settings.py"

- name: syncdb
  django_manage: command=syncdb
                 app_path="{{agora.root}}"
