---
- name: clone agora-ciudadana
  git: repo=https://github.com/pirata-cat/agora-ciudadana.git
       dest="{{agora.root}}"
       version=master

- name: create virtualenv
  shell: /bin/bash -c 'virtualenv {{agora.virtualenv.root}}'
  args:
    creates: "{{agora.virtualenv.root}}"

- name: install dependencies
  pip: requirements=requirements.txt
       virtualenv="{{agora.virtualenv.root}}"
       chdir="{{agora.root}}"

- name: install custom dependencies
  pip: name=psycopg2
       virtualenv="{{agora.virtualenv.root}}"

- name: install local config
  template: src=settings.py
            dest="{{agora.root}}/agora_site/custom_settings.py"

- template: src=agora_celery_launch.sh
            dest={{agora.root}}
            mode="0755"

- name: post-install processes
  django_manage: command='{{item}}'
                 app_path="{{agora.root}}"
                 virtualenv="{{agora.virtualenv.root}}"
  with_items:
    - 'syncdb --all --noinput'
    - 'migrate --fake --noinput'
    - 'rebuild_index --noinput'
    - 'check_permissions'
    - 'createsuperuser --username {{agora.user}} --email {{admin.email}} --noinput'
    - 'compilemessages'
    - 'collectstatic --noinput'
  when: agora_db|failed

- debug: msg='login as {{agora.user}} and execute django-admin.py changepassword {{agora.user}} to set a password'
  when: agora_db|failed

- debug: msg='you must execute too make dependencies && make all on Agora dir'
