---
- name: setup repositories keys
  apt_key: id='{{item.id}}' url='{{item.url}}'
  with_items:
    - { id: '7BD9BF62', url: 'http://nginx.org/keys/nginx_signing.key' }
    - { id: 'ACCC4CF8', url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc' }

- name: setup repositories
  apt_repository: repo='deb {{item}}' update_cache=yes
  with_items:
    - 'http://nginx.org/packages/debian/ {{debian_release}} nginx'
    - 'http://apt.postgresql.org/pub/repos/apt/ {{debian_release}}-pgdg main 9.4'

- name: install dependencies
  apt: name={{item}} force=yes
  with_items:
    - nginx
    - git
    - python2.7
    - python2.7-dev
    - virtualenvwrapper
    - rabbitmq-server
    - gettext
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - postgresql-9.4
    - postgresql-client-9.4
    - libpq-dev
    - python-pip
    - libmemcached-dev
    - zlib1g-dev
    - supervisor
    - uwsgi

- pip: name=psycopg2

- name: create system user
  user: name="{{agora.user}}" system=yes shell=/bin/bash

- action: shell grep "{{agora.user}}:!:" /etc/shadow
  ignore_errors: yes
  register: shadow_test
  changed_when: False

- name: lock system user
  shell: "passwd -d {{agora.user}} && passwd -l {{agora.user}}"
  when: shadow_test|failed

- include: services.yml

- include: postgres.yml
  sudo: yes
  sudo_user: postgres

- include: agora.yml
  sudo: yes
  sudo_user: "{{agora.user}}"

- template: src=agora-supervisor.conf
           dest=/etc/supervisor/conf.d/agora.conf
  notify: restart supervisor

- template: src=agora-uwsgi.ini
           dest="{{agora.virtualenv.root}}/agora-uwsgi.ini"
  notify: restart supervisor

- template: src=agora-celery.conf
           dest=/etc/supervisor/conf.d/agora-celery.conf
  notify: restart supervisor

- ufw: rule=allow
       port="{{item}}"
       proto=tcp
  with_items:
    - 80
    - 443
